application: encima-potato
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "latest"
- name: PIL
  version: "latest"
- name: MySQLdb
  version: "latest"

builtins:
- django_wsgi: on

env_variables:
    DJANGO_SETTINGS_MODULE: 'potato.settings'
skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^env/.*$

handlers:
- url: /static/
  static_dir: blog/static